import { CHECKLIST_TEMPLATE } from "./checklist";

// Helper to create a checklist with some items completed
function makeChecklist(completedCount, completedBy) {
  return CHECKLIST_TEMPLATE.map((item, i) => ({
    ...item,
    id: `item-${i}`,
    completed: i < completedCount,
    completedBy: i < completedCount ? completedBy : null,
    completedAt: i < completedCount ? "2026-03-21T14:30:00.000Z" : null,
  }));
}

export const MOCK_DELIVERIES = [
  {
    id: "mock-1",
    unitYear: "2026",
    unitMake: "Grand Design",
    unitModel: "Imagine 2800BH",
    stockNumber: "ROA-4521",
    customerName: "James & Sarah Mitchell",
    customerPhone: "(405) 555-0142",
    customerEmail: "j.mitchell@email.com",
    assignedTo: "Mike Torres",
    scheduledDate: "2026-03-22",
    status: "inspection",
    notes: "Customer requested extra walkthrough on electrical system. First-time RV owners.",
    checklist: makeChecklist(18, "mike@roa-rv.com"),
    createdAt: "2026-03-18",
  },
  {
    id: "mock-2",
    unitYear: "2025",
    unitMake: "Keystone",
    unitModel: "Cougar 29RKS",
    stockNumber: "ROA-4498",
    customerName: "Robert Chen",
    customerPhone: "(918) 555-0287",
    customerEmail: "rchen@email.com",
    assignedTo: "Lisa Nguyen",
    scheduledDate: "2026-03-22",
    status: "ready",
    notes: "",
    checklist: makeChecklist(32, "lisa@roa-rv.com"),
    createdAt: "2026-03-15",
  },
  {
    id: "mock-3",
    unitYear: "2026",
    unitMake: "Winnebago",
    unitModel: "View 24D",
    stockNumber: "ROA-4533",
    customerName: "Patricia Hernandez",
    customerPhone: "(580) 555-0193",
    customerEmail: "pat.h@email.com",
    assignedTo: "Mike Torres",
    scheduledDate: "2026-03-24",
    status: "prep",
    notes: "Hitch install included in sale. Customer picking up Saturday morning.",
    checklist: makeChecklist(8, "mike@roa-rv.com"),
    createdAt: "2026-03-19",
  },
  {
    id: "mock-4",
    unitYear: "2025",
    unitMake: "Forest River",
    unitModel: "Rockwood 2706WS",
    stockNumber: "ROA-4477",
    customerName: "David & Karen Thompson",
    customerPhone: "(405) 555-0368",
    customerEmail: "dthompson@email.com",
    assignedTo: "Lisa Nguyen",
    scheduledDate: "2026-03-25",
    status: "pending",
    notes: "",
    checklist: makeChecklist(0, null),
    createdAt: "2026-03-20",
  },
  {
    id: "mock-5",
    unitYear: "2026",
    unitMake: "Airstream",
    unitModel: "Basecamp 20X",
    stockNumber: "ROA-4540",
    customerName: "Emily Watson",
    customerPhone: "(918) 555-0411",
    customerEmail: "ewatson@email.com",
    assignedTo: "Mike Torres",
    scheduledDate: "2026-03-26",
    status: "pending",
    notes: "Customer wants solar panel walkthrough. Adding dealer-installed solar package.",
    checklist: makeChecklist(0, null),
    createdAt: "2026-03-21",
  },
  {
    id: "mock-6",
    unitYear: "2025",
    unitMake: "Jayco",
    unitModel: "Jay Flight 264BH",
    stockNumber: "ROA-4461",
    customerName: "Marcus Johnson",
    customerPhone: "(580) 555-0529",
    customerEmail: "mjohnson@email.com",
    assignedTo: "Lisa Nguyen",
    scheduledDate: "2026-03-19",
    status: "completed",
    notes: "Repeat customer — traded in 2022 model.",
    checklist: makeChecklist(34, "lisa@roa-rv.com"),
    createdAt: "2026-03-12",
  },
  {
    id: "mock-7",
    unitYear: "2026",
    unitMake: "Thor",
    unitModel: "Sequence 20L",
    stockNumber: "ROA-4552",
    customerName: "Amanda & Brian Foster",
    customerPhone: "(405) 555-0644",
    customerEmail: "abfoster@email.com",
    assignedTo: "Mike Torres",
    scheduledDate: "2026-03-27",
    status: "pending",
    notes: "",
    checklist: makeChecklist(0, null),
    createdAt: "2026-03-22",
  },
  {
    id: "mock-8",
    unitYear: "2025",
    unitMake: "Coachmen",
    unitModel: "Catalina 283RKS",
    stockNumber: "ROA-4489",
    customerName: "Steven Park",
    customerPhone: "(918) 555-0773",
    customerEmail: "spark@email.com",
    assignedTo: "Lisa Nguyen",
    scheduledDate: "2026-03-17",
    status: "completed",
    notes: "",
    checklist: makeChecklist(34, "lisa@roa-rv.com"),
    createdAt: "2026-03-10",
  },
];
